dist: xenial
sudo: required

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) success $DISCORD_WEBHOOK_URL
after_failure:
  - bash <(curl -s https://raw.githubusercontent.com/common-theory/travis-ci-discord-webhook/master/send.sh) failure $DISCORD_WEBHOOK_URL

language: node_js
node_js:
  10

addons:
  apt:
    sources:
      - sourceline: 'ppa:longsleep/golang-backports'
    update: true
    packages:
      - golang-go

before_script:
  - go get -u github.com/ipfs/ipfs-update
  - ipfs-update install v0.4.18

script:
  - ipfs init
  - ipfs daemon &
  - npm run ganache &
  - npm run coverage
