sudo: required

language: node_js
node_js:
  10

addons:
  apt:
    packages:
      - golang-go

script:
  - wget https://github.com/ipfs/go-ipfs/releases/download/v0.4.17/go-ipfs_v0.4.17_linux-386.tar.gz
  - tar -xvf go-ipfs_v0.4.17_linux-386.tar.gz
  - sudo mv ./go-ipfs/ipfs /usr/local/bin/ipfs
  - rm -rf go-ipfs
  - rm go-ipfs_v0.4.17_linux-386.tar.gz
  - npm run ganache &
  - npm run coverage
  - npm run upload-coverage
